[package]
name = "rust_kafka_like"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_kafka_like"
path = "src/lib.rs"


[[example]]
name = "mulch-send-recv"
path = "examples/mulch-send-recv.rs"

[dependencies]
