name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install nightly Rust (2024 Edition)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Verify Rust version
        run: rustc --version

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Run example
        run: cargo run --example mulch-send-recv
